name: Ci
on: [push, pull_request]
jobs:
  build-and-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: yarn install, compile
        run: |
          yarn install
          yarn build
          yarn test

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: check diff
          path: tests/COMPAREDIFF
